# Generated by Django 5.1.5 on 2025-01-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_id', models.CharField(max_length=50, unique=True)),
                ('last_maintenance_date', models.DateField()),
                ('efficiency', models.FloatField()),
                ('current_output', models.FloatField()),
            ],
        ),
    ]
