# Generated by Django 5.1.5 on 2025-01-28 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_solarpanel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('num_solar_panels', models.IntegerField()),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='energydata',
            name='household',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='energy_data', to='api.household'),
        ),
        migrations.AddField(
            model_name='solarpanel',
            name='household',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solar_panels', to='api.household'),
        ),
    ]
