# Generated by Django 5.1.5 on 2025-01-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_energydata_household_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='house_size',
            field=models.FloatField(default=2514),
        ),
    ]
